name: Deploy EduHabit

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 40m
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /home/Nabigh/eduhabbit
            timeout 60 git pull origin master
            export NODE_OPTIONS="--max-old-space-size=1024"
            timeout 300 npm install
            timeout 120 npm rebuild better-sqlite3
            timeout 1800 npm run build
            timeout 60 npm run db:migrate
            sudo systemctl restart eduhabit
